#!/bin/bash --login

######### Start the mail message file ################################


echo "" > $LOGDIR/mailHeader
echo "" > $LOGDIR/header
echo "Script end: `date`" >> $LOGDIR/header


echo "" >> $LOGDIR/mailMessage
echo "" >> $LOGDIR/mailMessage
echo "" >> $LOGDIR/mailHeader
echo "" >> $LOGDIR/mailHeader
echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "_____________________________________ESMF EXTERNAL DEMOS AND TEST SUMMARY___________________________" >> $LOGDIR/header

echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "                                            " >> $LOGDIR/header
echo "                                            " >> $LOGDIR/header
echo "                          DOC BUILD">> $LOGDIR/header
echo "               BUILD       INSTALL    OS.COMPILER.COMM.ABI       external demos">> $LOGDIR/header


echo "________________________________________________________________________________________" >> $LOGDIR/header

echo "               PASS/FAIL   PASS/FAIL                              PASS/FAIL/SKIP">> $LOGDIR/header

echo "_________________________________________________________________________________________" >> $LOGDIR/header


############################# Put the mail message together and mail it ####################

awk '{if ($1 ~/PASS/) printf ("%-16s%-12s%-8s%-25s%13s\n",  $3, $1, $2, $4, $5) ;else  printf ("%-10s%-20s%-10s\n", $2, $1,  $3 )}'  $LOGDIR/summary > $LOGDIR/newsummary

cat $LOGDIR/mailHeader $LOGDIR/header $LOGDIR/newsummary > $LOGDIR/sum
cat $LOGDIR/sum $LOGDIR/mailMessage > $LOGDIR/newMailMessage
echo "" >>  $LOGDIR/newMailMessage
echo " The tarballs of the tests and examples directories can be found at:" >>  $LOGDIR/newMailMessage
echo " $LOGDIR." >>  $LOGDIR/newMailMessage
echo " These tarballs contain the *Log and *stdout files only, not the executables." >>  $LOGDIR/newMailMessage
echo " This directory also contains failed build output files with the naming convention of " >>  $LOGDIR/newMailMessage
echo " build_ESMF_BOPT_(day)(platform)ESMF_OS ESMF_ABI ESMF_COMPILER ESMF_COMM." >>  $LOGDIR/newMailMessage
echo " For example, if the build fails on longs on the 19th of the month with ESMF_BOPT=g, the file " >>  $LOGDIR/newMailMessage
echo " would be called 'build_g_19longslinux32pgimpiuni'." >>  $LOGDIR/newMailMessage
