
Currently Loaded Modules:
  1) python/3.7.5   3) mpich/3.3.2   5) hdf5/1.10.6      7) netcdf/4.7.4
  2) pgi/2019       4) szip/2.1.1    6) pnetcdf/1.12.1

 

/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
dirname: missing operand
Try 'dirname --help' for more information.
Using built-in specs.
COLLECT_GCC=gfortran
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/version.pgf90: line 14: /pgf90: No such file or directory
which: no mpiCC in (/apps/mpich-3.3.2/netcdf-4.7.4/bin:/apps/mpich-3.3.2/pnetcdf-1.12.1/bin:/apps/mpich-3.3.2/hdf5-1.10.6/bin:/apps/mpich-3.3.2/mpich-3.3.2/bin:/apps/pgi-2019/pgi-2019-19.9/linux86-64-llvm/2019/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/lib64/qt-3.3/bin:/apps/sbin:/apps/bin:/opt/slurm/bin)
which: no mpiCC in (/apps/mpich-3.3.2/netcdf-4.7.4/bin:/apps/mpich-3.3.2/pnetcdf-1.12.1/bin:/apps/mpich-3.3.2/hdf5-1.10.6/bin:/apps/mpich-3.3.2/mpich-3.3.2/bin:/apps/pgi-2019/pgi-2019-19.9/linux86-64-llvm/2019/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/lib64/qt-3.3/bin:/apps/sbin:/apps/bin:/opt/slurm/bin)
which: no mpiCC in (/apps/mpich-3.3.2/netcdf-4.7.4/bin:/apps/mpich-3.3.2/pnetcdf-1.12.1/bin:/apps/mpich-3.3.2/hdf5-1.10.6/bin:/apps/mpich-3.3.2/mpich-3.3.2/bin:/apps/pgi-2019/pgi-2019-19.9/linux86-64-llvm/2019/bin:/sbin:/usr/sbin:/bin:/usr/bin:/usr/lib64/qt-3.3/bin:/apps/sbin:/apps/bin:/opt/slurm/bin)
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
/work/noaa/da/mpotts/pgi_2019_mpich_O/scripts/compiler.pgcxx: line 4: mpiCC: command not found
make[8]: mpiCC: Command not found
make[8]: *** [/work/noaa/da/mpotts/pgi_2019_mpich_O/obj/objO/Linux.pgi.64.mpich.default/binary.o] Error 127
make[7]: *** [esmflib] Error 2
make[6]: *** [tree_lib] Error 2
make[5]: *** [tree] Error 1
make[4]: *** [tree] Error 1
make[3]: *** [tree] Error 1
make[2]: *** [tree] Error 1
make[1]: *** [build_libs] Error 2
make: *** [lib] Error 2
