#!/bin/bash 
rfile=$1


export homedir=/project/esmf/himanshu/esmf_test/cronjobs/daily/gfortran_clang
export PATH=~/bin:$PATH

############################### Read the file for log directory and email recipient #######

datestamp=`date +%y%m`
logfile="${datestamp}_test"
echo " The logfile is $logfile"
here=`pwd`


if grep -i "LOG_DIR1" $rfile > tmp
then
        read location log_dir log_tmp < tmp
        cd $log_dir
        if test ! -d  $logfile
        then
                # Make new directory if doesn't exist
                mkdir $logfile
        fi
        cd $here
        echo "LOGDIR1 is $log_dir/$logfile"
        export LOGDIR=$log_dir/$logfile
fi

	echo "LOGDIR=$LOGDIR"

if grep -i "email_to" $rfile > tmp
then
        read location emailuser < tmp
        echo "Email user is $emailuser"
fi

if grep -i "email_title" $rfile > tmp
then
        read location email_title < tmp
        echo "Email title is $email_title"
fi


rm -f tmp

rm -f $LOGDIR/mailMessage
rm -f $LOGDIR/newMailMessage
rm -f $LOGDIR/header
rm -f $LOGDIR/mailHeader
rm -f $LOGDIR/newsummary
rm -f $LOGDIR/sum
rm -f $LOGDIR/summary

echo "" > $LOGDIR/header
echo "Script start time: `date`" >> $LOGDIR/header

# Set test status as green, assume it will run clean
echo "Test_results:green" > $LOGDIR/Test_Status

#Set day of the week
echo "Day_of_Week:`date +%A`" > $LOGDIR/Day_Started

#Set Number of test failure
echo "0" > $LOGDIR/Test_Failures

cd $homedir

chk_out_scripts

chmod a+x $homedir/bin/*

$homedir/bin/chk_out_esmf $rfile ESMF_Catania_gfortran_clang

export PATH_org=$PATH
############################# Run the tests ###############################

 #source /glade/u/apps/ch/opt/lmod/7.5.3/lmod/lmod/init/bash
number=1
while grep "^$number " $rfile >tmp
do
	# Get the computer information
        read num location directory hostname abi site comp comm u_tests u_tests_type sys_test_type threaded mpmd ck_out_opt tag < tmp
        echo "$location $directory $hostname $abi $site $comp $comm $u_tests $u_tests_type $sys_test_type $threaded $mpmd $ck_out_opt $tag"
        cat tmp
	source /project/esmf/Modules/init/bash
        export MODULEPATH=/project/esmf/Modules/modulefiles
	export ESMF_OS=`uname -s`
	export ESMF_DIR=/project/esmf/himanshu/esmf_test/cronjobs/daily/gfortran_clang/esmf
	export LOGTMP=$log_tmp
	export OPT=g
	export ESMF_BOPT=g
	export SYS_TEST_TYPE=$sys_test_type
	export U_TESTS=$u_tests
	export U_TESTS_TYPE=$u_tests_type
	export ESMF_ABI=$abi
	export ESMF_SITE=$site
	export ESMF_COMPILER=$comp
	export ESMF_COMM=$comm
	export THREADED=$threaded
	export ESMF_TESTEXHAUSTIVE=$u_tests
	#export ESMF_NETCDF=nc-config
        export ESMF_INSTALL_PREFIX=/project/esmf/himanshu/esmf_test/cronjobs/daily/gfortran_clang/install_dir
        #export ESMF_TESTHARNESS_FIELD=RUN_ESMF_TestHarnessFieldUNI_1
        #export ESMF_TESTHARNESS_ARRAY=RUN_ESMF_TestHarnessArrayUNI_2
	#export ESMF_MPIRUN=/home/oehmke/ESMF/HEAD/src/Infrastructure/stubs/mpiuni/mpirun

        rm -rf $ESMF_INSTALL_PREFIX/*
        if [[ $threaded = "THREADED" ]]
        then
		echo $ESMF_TESTWITHTHREADS
                export ESMF_TESTWITHTHREADS=ON 
        else
                export ESMF_TESTWITHTHREADS=OFF
        fi 
        if [[ $u_tests = "EX" ]]
        then
		echo $ESMF_TESTEXHAUSTIVE
                export ESMF_TESTEXHAUSTIVE=ON
        else 
                export ESMF_TESTEXHAUSTIVE=OFF
        fi 

        if [[ $mpmd = "MPMD" ]]
        then
		echo $ESMF_TESTMPMD
                export ESMF_TESTMPMD=ON
        else
                export ESMF_TESTMPMD=OFF
        fi

	#export MODULEPATH=$MODULEPATH":/project/esmf/modulefiles"
       	
	if [[ $ESMF_COMPILER = "gf" ]]
        then
            export ESMF_COMPILER=gfortranclang
            module purge
            module load GCC/Homebrew/9.3.0_1/gcc GCC/Homebrew/9.3.0_1/netcdf/4.7.4s
            export ESMF_NETCDF=nc-config
        fi 

        if [[ $ESMF_COMPILER = "gc" ]]
        then
            export ESMF_COMPILER=gfortranclang
	    module purge
            module load GCC/Homebrew/9.3.0_1/gcc GCC/Homebrew/9.3.0_1/mpich/3.3.2 GCC/Homebrew/9.3.0_1/netcdf/4.7.4s
	    export ESMF_NETCDF=nc-config
        fi
        
        if [[ $ESMF_COMM = "mpiuni" ]]
        then
             export ESMF_COMM=mpiuni   
        fi

	if [[ $ESMF_COMM = "mpich3" ]]
        then
             export ESMF_COMM=mpich3
             
        fi

	export my_make="gmake -j64"

        export RFile=$rfile
	echo "ESMF_DIR = $ESMF_DIR"
	cd $ESMF_DIR
        rm -rf $ESMF_INSTALL_PREFIX/*
	#$homedir/test_tutorial
	$homedir/bin/test_esmf_noq
	export OPT=O
	export ESMF_BOPT=O
	$homedir/bin/test_esmf_noq
	cd $homedir
        number=`expr $number + 1`
        echo "number = $number"
done
cd $homedir

#cd /scratch/esmf_test/cronjobs/daily/gfortran_clang/esmf/
#rm -rf *

echo "end of test script"
exit

