Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "netcdf4/4.7.4"
   Try: "module spider netcdf4/4.7.4" to see how to load the module(s).



/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
which: no mpif90 in (/usr/local/other/python/GEOSpyD/2019.10_py3.7/2020-01-15/bin:/home/mapotts1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/slurm/bin:/home/mapotts1/cmake/bin:/discover/nobackup/mapotts1/spack/bin)
which: no mpicxx in (/usr/local/other/python/GEOSpyD/2019.10_py3.7/2020-01-15/bin:/home/mapotts1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/slurm/bin:/home/mapotts1/cmake/bin:/discover/nobackup/mapotts1/spack/bin)
which: no mpif90 in (/usr/local/other/python/GEOSpyD/2019.10_py3.7/2020-01-15/bin:/home/mapotts1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/slurm/bin:/home/mapotts1/cmake/bin:/discover/nobackup/mapotts1/spack/bin)
which: no mpif90 in (/usr/local/other/python/GEOSpyD/2019.10_py3.7/2020-01-15/bin:/home/mapotts1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/slurm/bin:/home/mapotts1/cmake/bin:/discover/nobackup/mapotts1/spack/bin)
which: no mpicxx in (/usr/local/other/python/GEOSpyD/2019.10_py3.7/2020-01-15/bin:/home/mapotts1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/slurm/bin:/home/mapotts1/cmake/bin:/discover/nobackup/mapotts1/spack/bin)
which: no mpicxx in (/usr/local/other/python/GEOSpyD/2019.10_py3.7/2020-01-15/bin:/home/mapotts1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/gnome/bin:/usr/slurm/bin:/home/mapotts1/cmake/bin:/discover/nobackup/mapotts1/spack/bin)
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/scripts/compiler.pgcxx: line 4: mpicxx: command not found
make[8]: mpicxx: Command not found
make[8]: *** [/gpfsm/dnb04/projects/p98/mpotts/esmf/pgi_2020_mpt_g/obj/objg/Linux.pgi.64.mpt.default/binary.o] Error 127
make[7]: *** [esmflib] Error 2
make[6]: *** [tree_lib] Error 2
make[5]: *** [tree] Error 1
make[4]: *** [tree] Error 1
make[3]: *** [tree] Error 1
make[2]: *** [tree] Error 1
make[1]: *** [build_libs] Error 2
make: *** [lib] Error 2
