#!/bin/bash -l

esmftestroot=/usr/local/esmf/esmf-testing
cd ${esmftestroot}/esmf-test-scripts
git remote update
git pull -X theirs --no-edit

cd ${esmftestroot}

# Modules haven't been set up on fairy. However, we can use "spack load" in place of
# "module load" to accomplish the same thing. To enable this translation, create a
# function mapping "module" commands to "spack" commands.
module() {
   if [[ "$1" == "list" ]]; then
      # It may or may not be correct to add the extra arguments ("${@:2}"), but for now it
      # doesn't matter since the "module list" commands generated by the test scripts
      # don't currently have any extra arguments
      spack find --loaded "${@:2}"
   else
      # This simple mapping won't work for all commands, but it works for the simple
      # "module load" commands we need it for.
      spack "$@"
   fi
}
export -f module

# Wrap the python script in a call from an AppleScript to get the cron job to run faster
# (From https://stackoverflow.com/questions/74793041/why-does-selenium-python-script-run-really-slow-in-cron-compared-to-vscode)
# (Without a GUI attached, we can't use the "tell application \"Terminal\"" approach from
# that post, but we can still execute a shell script directly via osascript.)
osascript -e "do shell script \"cd ${esmftestroot} && python3 ./esmf-test-scripts/python_scripts/test_esmf.py -m fairy -r ${esmftestroot} >& ${esmftestroot}/test_esmf_fairy.log\""

