#!/usr/lpp/ssp/expect/bin/expect --

set sfuser [lindex $argv 0]
set tag [lindex $argv 1]
send_user " tag is $tag"

set timeout 3600

if { $tag == "" } {

	spawn  cvs -z3 -d:ext:$sfuser@esmf.cvs.sourceforge.net:/cvsroot/esmf co -P use_test_cases

} else {

	spawn cvs -z3 -d:ext:$sfuser@esmf.cvs.sourceforge.net:/cvsroot/esmf co -P -r $tag use_test_cases
}


expect {
	"password: "
			{

                                send "$sfpword\r"

                        }
        "(yes/no)?"
                        {

                                send "yes\r"

                                exp_continue


                        }
        "(yes/no)? "
                        {

                                send "yes\r"

                                exp_continue

                        }

        }



expect eof


