machine: acorn
account: GFS-DEV
queue: dev
git-https: True
scheduler: pbs
corespernode: 128
compiler: [intel,gfortran]
branch: [develop]
intel:
     versions: 
       2019.3: 
         compiler: intel/19.1.3.304          
         netcdf: netcdf/4.7.4
         hdf5: hdf5/1.10.6   
         mpi:
           mpi: 
             module: cray-mpich/8.1.7
             pythontest: False
         extra_env_vars: 
            var1: ESMF_OS=Linux
            var2: ESMF_CXXCOMPILER=CC
            var3: ESMF_F90COMPILER=ftn
            var4: ESMF_CXXLINKER=CC
            var5: ESMF_F90LINKER=ftn
            var6: ESMF_MPIRUN=mpirun.unicos
            var7: ESMF_CXXCOMPILECPPFLAGS=-fPIC
            var8: ESMF_CXXLINKOPTS="-fPIC -lnetcdff -lnetcdff"
            var9: ESMF_NETCDF=nc-config
         extra_commands: 
            cmd1: "sed -i 's/^aprun/mpiexec/' scripts/mpirun.unicos"
            cmd2: "sed -i 's/lmpi++/lfmpich/' build_config/Linux.intel.default/build_rules.mk"
     extramodule: PrgEnv-intel cray-pals craype
     unloadmodule: "PrgEnv-cray PrgEnv-gnu"
gfortran:
     versions: 
       10.3.0: 
         compiler: gcc/10.3.0
         netcdf: netcdf
         hdf5: hdf5
         mpi:
           mpich3: 
             module: cray-mpich/8.1.7
             pythontest: False
         extra_env_vars: 
            var1: ESMF_OS=Linux
            var2: ESMF_CXXCOMPILER=CC
            var3: ESMF_F90COMPILER=ftn
            var4: ESMF_CXXLINKER=CC
            var5: ESMF_F90LINKER=ftn
            var6: ESMF_MPIRUN=mpirun.unicos
            var7: ESMF_F90COMPILEOPTS="-fallow-argument-mismatch -fallow-invalid-boz"
            var8: ESMF_NFCONFIG=nf-config
            var9: ESMF_CXXLINKOPTS="-fPIC -lnetcdff -lnetcdff"
         extra_commands: 
            cmd1: "sed -i 's/aprun/mpiexec/' scripts/mpirun.unicos"
     extramodule: PrgEnv-gnu cray-pals craype
     unloadmodule: "PrgEnv-cray PrgEnv-intel"
