machine: cheyenne
account: p93300606
queue: regular
partition: None
scheduler: pbs
corespernode: 36
compiler: [gfortran, intel, nvhpc]
headnodename: cheyenne6
branch: [develop,v8.3.0]
#nuopcbranch: develop
gfortran:
  test_time: "2:00:00"
  versions:
    7.4.0:
      compiler: gnu/7.4.0
      netcdf: netcdf/4.7.3
      mpi:
        openmpi:
          module: openmpi/4.0.3
      extra_env_vars:
        var1: ESMF_F90COMPILER=mpif90
    9.1.0:
      compiler: gnu/9.1.0
      netcdf: netcdf/4.7.3
      mpi:
        openmpi:
          module: openmpi/4.0.5
        mpt:
          module: mpt/2.22
      extra_env_vars:
        var1: ESMF_F90COMPILER=mpif90
    10.1.0:
      compiler: gnu/10.1.0
      netcdf: netcdf/4.7.4
      mpi:
        openmpi:
          module: openmpi/4.0.5
        mpt:
          module: mpt/2.23
      extra_env_vars:
        var1: ESMF_F90COMPILER=mpif90
  extramodule: cmake
intel:
  test_time: "3:00:00"
  versions:
    18.0.5:
      compiler: intel/18.0.5
      netcdf: netcdf/4.6.3
      mpi:
        mpiuni:
          module: None
        mpt:
          module: mpt/2.19
        openmpi:
          module: openmpi/3.1.4
          pythontest: True
        intelmpi:
          module: impi/2018.4.274
          pythontest: True
  extramodule: python cmake
nvhpc:
  test_time: "3:00:00"
  versions:
    22.2:
      compiler: nvhpc/22.2
      netcdf: netcdf/4.8.1
      mpi:
        mpt:
          module: mpt/2.25
  extramodule: python cmake
