machine:
  name: cheyenne
  cores_per_node: 36
  head_node_name: cheyenne6
  scheduler:
    type: pbs
    account: p93300606
    queue: regular
    partition: None

test:
  esmf_branch: [develop,release/8.4.0]
  nuopc_branch: [develop,release/8.4.0]

matrix:
  gfortran:
    test_time: "2:00:00"
    versions:
      7.4.0:
        compiler: gnu/7.4.0
        netcdf: netcdf/4.7.3
        extra_module: python/3.7.9
        mpi:
          openmpi:
            module: openmpi/4.0.3
      9.1.0:
        compiler: gnu/9.1.0
        netcdf: netcdf/4.7.3
        extra_module: python/3.7.9
        mpi:
          openmpi:
            module: openmpi/4.0.5
          mpt:
            module: mpt/2.22
      10.1.0:
        compiler: gnu/10.1.0
        netcdf: netcdf/4.7.4
        mpi:
          openmpi:
            module: openmpi/4.0.5
          mpt:
            module: mpt/2.23
        extra_env_vars:
          - ESMPY_DATA_DIR="/glade/work/theurich/esmf-test-data/grids"
        esmpy:
          python: python/3.7.9

  intel:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      18.0.5:
        compiler: intel/18.0.5
        netcdf: netcdf/4.6.3
        mpi:
          mpiuni:
            module: None
          mpt:
            module: mpt/2.19
          openmpi:
            module: openmpi/3.1.4
          intelmpi:
            module: impi/2018.4.274
        extra_env_vars:
          - ESMPY_DATA_DIR="/glade/work/theurich/esmf-test-data/grids"
        esmpy:
          python: python/3.7.9

  nvhpc:
    test_time: "3:00:00"
    versions:
      22.2:
        compiler: nvhpc/22.2
        netcdf: netcdf/4.8.1
        extra_module: python/3.7.9
        mpi:
          mpiuni:
            module: None
          mpt:
            module: mpt/2.25
      21.11:
        compiler: nvhpc/21.11
        netcdf: netcdf/4.8.1
        extra_module: python/3.7.9
        mpi:
          openmpi:
            module: openmpi/4.1.1
