machine:
  name: chianti-no-modules
  cores_per_node: 8
  scheduler: None

test:
  esmf_branch: [develop,feature/large-messages]
  nuopc_branch: [develop,v8.3.0]

matrix:
  intel:
    versions:
      18.0.5:
        compiler: intel/18.0.5.274
        netcdf: netcdf/4.7.0
        mpi:
          intelmpi:
            module: impi/2018.4.274
          mpiuni:
            module: None
  gfortran:
    versions:
      9.3.0:
        compiler: 9.3.0
        netcdf: None
        mpi:
          openmpi:
            module: 3.1.6
          mpiuni:
            module: None
        extra_env_vars:
          - ESMF_NETCDF=/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-9.3.0/netcdf-c-4.7.4-mh42cmw5oougqeytguqxjkkrrd2bfdsl/bin/nc-config
          - ESMF_NFCONFIG=/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-9.3.0/netcdf-fortran-4.5.3-7cigsuiobyasv6mbext7pmabw5fhzo6y/bin/nf-config
          - CC=/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-7.5.0/gcc-9.3.0-3ltccu6cenbq/bin/gcc
          - CXX=/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-7.5.0/gcc-9.3.0-3ltccu6cenbq/bin/g++
          - FC=/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-7.5.0/gcc-9.3.0-3ltccu6cenbq/bin/gfortran
          - ESMF_NFCONFIG=nf-config
          - PATH=/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-9.3.0/openmpi-3.1.6-jnhkylwskoutgnisw5k4agyzw77xr35b/bin:$PATH
          - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-9.3.0/openmpi-3.1.6-jnhkylwskoutgnisw5k4agyzw77xr35b/lib
          - LIBRARY_PATH=$LIBRARY_PATH:/home/mpotts/spack/opt/spack/linux-linuxmint19-skylake/gcc-9.3.0/openmpi-3.1.6-jnhkylwskoutgnisw5k4agyzw77xr35b/lib

