machine:
  name: derecho
  cores_per_node: 128
  scheduler:
    type: pbs
    account: p93300606
    queue: main
    partition: None

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]

#  filter:
#    compiler: [gfortran]

matrix:

  gfortran:
    build_time: "2:00:00"
    test_time: "2:00:00"
    versions:
      12.2.0_pio2.5.10:
        compiler: gcc/12.2.0
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.06 gcc/12.2.0 cray-mpich/8.1.25 cmake parallelio/2.5.10
        mpi:
          mpi:
            module: cray-mpich/8.1.25
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
              - ESMF_PIO=external
              - ESMF_PIO_INCLUDE="$PIO/include"
              - ESMF_PIO_LIBPATH="$PIO/lib"
      12.2.0_pio2.6.2:
        compiler: gcc/12.2.0
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.09 cmake parallelio/2.6.2
        mpi:
          mpi:
            module: cray-mpich/8.1.27
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
              - ESMF_PIO=external
              - ESMF_PIO_INCLUDE="$PIO/include"
              - ESMF_PIO_LIBPATH="$PIO/lib"

  intel:
    build_time: "2:00:00"
    test_time: "2:00:00"
    versions:
      2023.2.1:
        compiler: intel/2023.2.1
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.09 cmake
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.27
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
      2023.2.1-classic:
        compiler: intel-classic/2023.2.1
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.09 cmake
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.27
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
      2023.2.1-oneAPI:
        compiler: intel-oneapi/2023.2.1
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.09 cmake
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.27
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec

  nvhpc:
    build_time: "2:00:00"
    test_time: "2:00:00"
    versions:
      23.7:
        compiler: nvhpc/23.7
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.09 cmake
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.27
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec

  cce:
    build_time: "2:00:00"
    test_time: "2:00:00"
    versions:
      15.0.1:
        compiler: cce/15.0.1
        netcdf: netcdf/4.9.2
        extra_module: ncarenv/23.06 cmake
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.25
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
