machine:
  name: fairy
  cores_per_node: 8
  scheduler: None
  # Since we don't submit to compute nodes on this machine, there is no notion of a head node
  # (this bypasses the ssh'ing to the head node in doing the ESMPy installation)
  head_node_name: null

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]

matrix:
  gfortran:
    versions:
      14.2.0:
        compiler: gcc/14.2.0
        mpi:
          openmpi:
            module: openmpi/5.0.8
            netcdf: netcdf-c/4.9.2 netcdf-fortran/4.6.2
        extra_env_vars:
          - ESMPY_DATA_DIR="/usr/local/esmf/esmf-testing/esmf-test-data/grids"
        esmpy:
          # This python version corresponds to the suffix in environment-python3.11-numpy1.26.yml
          python: python3.11-numpy1.26
