machine:
  name: gaeaC5
  lustre: True
  rsync: /tmp
  wait_to_collect: True
  cores_per_node: 128
  scheduler:
    type: slurm
    cluster: c5
    account: esrl_bmcs
    queue: normal

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]
#  filter:
#    compiler: [intel,cce]

matrix:
  gfortran:
       test_time: "2:00:00"
       versions:
         12.3.0:
           compiler: gcc-native/12.3
           netcdf: cray-hdf5/1.12.2.9 cray-netcdf/4.9.0.9
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.28
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-gnu git cmake
           unload_module: PrgEnv-intel cray-mpich
  intel:
       test_time: "2:00:00"
       versions:
         2023.2.0-classic:
           compiler: intel-classic/2023.2.0
           netcdf: cray-hdf5/1.12.2.9 cray-netcdf/4.9.0.9
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.28
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git cmake cray-libsci/24.07.0
         2023.2.0:
           compiler: intel/2023.2.0
           netcdf: cray-hdf5/1.12.2.9 cray-netcdf/4.9.0.9
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.28
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git cmake cray-libsci/24.07.0
         2025.0.0:
           compiler: intel/2025.0
           netcdf: cray-hdf5/1.14.3.5 cray-netcdf/4.9.0.17
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.32
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git cmake cray-libsci
  cce:
       test_time: "2:00:00"
       versions:
         19.0.0:
           compiler: cce/19.0.0
           netcdf: cray-hdf5/1.12.2.11 cray-netcdf/4.9.0.11
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.32
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-cray git cmake
           unload_module: PrgEnv-intel cray-mpich
