machine:
  name: gaeaC5
  lustre: True
  cores_per_node: 128
  scheduler:
    type: slurm
    cluster: c5
    account: esrl_bmcs
    queue: normal

test:
  esmf_branch: [develop,patch/8.4.1]
  nuopc_branch: [develop,v8.4.0]
#  filter:
#    compiler: [intel]

matrix:
  gfortran:
       test_time: "2:00:00"
       versions:
         11.2.0:
           compiler: gcc/11.2.0
           netcdf: cray-hdf5/1.12.1.3 cray-netcdf/4.8.1.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.16
           extra_env_vars:
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-gnu git
           unload_module: darshan-runtime PrgEnv-intel cray-mpich
  intel:
       test_time: "2:00:00"
       versions:
         2022.0-classic:
           compiler: intel-classic/2022.0.2
           netcdf: cray-hdf5/1.12.1.3 cray-netcdf/4.8.1.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.16
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git
           unload_module: darshan-runtime
         2022.0:
           compiler: intel/2022.0.2
           netcdf: cray-hdf5/1.12.1.3 cray-netcdf/4.8.1.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.16
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git
           unload_module: darshan-runtime
         2022.0-oneAPI:
           compiler: intel-oneapi/2022.0.2
           netcdf: cray-hdf5/1.12.1.3 cray-netcdf/4.8.1.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.16
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git
           unload_module: darshan-runtime
