machine:
  name: gaeaC5
  lustre: True
  rsync: /tmp
  wait_to_collect: True
  cores_per_node: 128
  scheduler:
    type: slurm
    cluster: c5
    account: esrl_bmcs
    queue: normal

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]
#  filter:
#    compiler: [intel]

matrix:
  gfortran:
       test_time: "2:00:00"
       versions:
         12.2.0:
           compiler: gcc/12.2.0
           netcdf: cray-hdf5/1.12.2.3 cray-netcdf/4.9.0.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.25
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-gnu git cmake
           unload_module: darshan-runtime PrgEnv-intel cray-mpich
  intel:
       test_time: "2:00:00"
       versions:
         2023.1.0-classic:
           compiler: intel-classic/2023.1.0
           netcdf: cray-hdf5/1.12.2.3 cray-netcdf/4.9.0.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.25
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git cmake
           unload_module: darshan-runtime
         2023.1.0:
           compiler: intel/2023.1.0
           netcdf: cray-hdf5/1.12.2.3 cray-netcdf/4.9.0.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.25
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git cmake
           unload_module: darshan-runtime
         2023.1.0-oneAPI:
           compiler: intel-oneapi/2023.1.0
           netcdf: cray-hdf5/1.12.2.3 cray-netcdf/4.9.0.3
           mpi:
             mpiuni:
               module: None
             mpi:
               module: cray-mpich/8.1.25
               mpi_env_vars: [ESMF_MPILAUNCHOPTIONS=--exact]
           extra_env_vars:
             - ESMF_NETCDF_INCLUDE="$CRAY_NETCDF_PREFIX/include"
             - ESMF_NETCDF_LIBPATH="$CRAY_NETCDF_PREFIX/lib"
             - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
           extra_module: PrgEnv-intel git cmake
           unload_module: darshan-runtime
