reclone-artifacts: True
repos:
  esmf:
    https: https://github.com/esmf-org/esmf
    git: git@github.com:esmf-org/esmf
  nuopc:
    https: https://github.com/esmf-org/nuopc-app-prototypes
    git: git@github.com:esmf-org/nuopc-app-prototypes
  artifacts:
    https: https://github.com/rsdunlapiv/esmf-test-artifacts.git
    git: git@github.com:rsdunlapiv/esmf-test-artifacts.git
