reclone-artifacts: False
repos:
  esmf:
    https: https://github.com/esmf-org/esmf
    git: /scratch/cluster/dunlap/esmf-test-dev/safe/esmf
  nuopc:
    https: https://github.com/esmf-org/nuopc-app-prototypes
    git: /scratch/cluster/dunlap/esmf-test-dev/safe/nuopc-app-prototypes
  artifacts:
    https: https://github.com/rsdunlapiv/esmf-test-artifacts.git
    git: git@github.com:rsdunlapiv/esmf-test-artifacts.git
