machine:
  name: green
  cores_per_node: 8
  scheduler: None
  # Since we don't submit to compute nodes on this machine, there is no notion of a head node
  # (this bypasses the ssh'ing to the head node in doing the ESMPy installation)
  head_node_name: null

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]

matrix:
  gfortranclang:
    versions:
      12.2.0_14.0.0:
        compiler: gfortran-12.2.0_clang-14.0.0
        netcdf: netcdf-4.9.0
        mpi:
          openmpi:
            module: 4.1.4
            bopt: [g]
          mpiuni:
            module: None
            bopt: [g]
        extra_env_vars:
          - ESMF_TESTPERFORMANCE=OFF
          - ESMPY_DATA_DIR="/Users/sacks/projects/scratch/esmf-testing/esmf-test-data/grids"
          - ESMF_TEST_NUOPC_JULIA=ON
        esmpy:
          # This python version corresponds to the suffix in environment-python3.11.yml
          python: python3.11
