machine:
  name: green
  cores_per_node: 8
  scheduler: None

test:
  esmf_branch: [develop]
  nuopc_branch: [workaround/darwin-threaded-hang]

matrix:
  gfortranclang:
    versions:
      12.2.0_14.0.0:
        compiler: gfortran-12.2.0_clang-14.0.0
        netcdf: netcdf-4.9.0
        mpi:
          openmpi:
            module: 4.1.4
            bopt: [O,g]
          mpiuni:
            module: None
            bopt: [O,g]
