machine:
  name: grits
  cores_per_node: 8
  scheduler: None

test:
  esmf_branch: [feature/internal-state-cleanup]
  nuopc_branch: [develop]

matrix:
  gfortranclang:
    versions:
      12.2.0_14.0.0:
        compiler: gfortran-12.2.0_clang-14.0.0
        netcdf: netcdf-4.9.2
        mpi:
          mpich:
            module: 4.1.1
          mpiuni:
            module: None
