machine:
  name: gust
  cores_per_node: 128
  scheduler:
    type: pbs
    account: p93300606
    queue: main
    partition: None

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]

matrix:
  intel:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      2021.6:
        compiler: intel/2021.7.1
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
#      2022.1-classic:
#        compiler: ncarenv/22.08b intel/2022.1.0
#        netcdf: netcdf/4.8.1
#        mpi:
#          mpiuni:
#            module: None
#          mpi:
#            module: cray-mpich/8.1.18
#            mpi_env_vars:
#              - ESMF_MPIRUN=mpiexec
#      2022.2-oneAPI:
#        compiler: ncarenv/22.12 oneapi/2022.2.1
#        netcdf: netcdf/4.9.0
#        mpi:
#          mpiuni:
#            module: None
#          mpi:
#            module: cray-mpich/8.1.21
#            mpi_env_vars:
#              - ESMF_MPIRUN=mpiexec

  nvhpc:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      23.1:
        compiler: nvhpc/23.1
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec

  cce:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      15.0.0:
        compiler: cce/15.0.0
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
