machine:
  name: gust
  cores_per_node: 128
  scheduler:
    type: pbs
    account: p93300606
    queue: main
    partition: None

test:
  esmf_branch: [develop,v8.4.1]
  nuopc_branch: [develop,v8.4.1]

matrix:
  intel:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      2021.7.1:
        compiler: intel/2021.7.1
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
        unload_module: cray-libsci
      2023.0-oneAPI:
        compiler: oneapi/2023.0.0
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
        unload_module: cray-libsci

  nvhpc:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      23.1:
        compiler: nvhpc/23.1
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec

  cce:
    build_time: "2:00:00"
    test_time: "3:00:00"
    versions:
      15.0.0:
        compiler: cce/15.0.0
        netcdf: netcdf/4.9.0
        mpi:
          mpiuni:
            module: None
          mpi:
            module: cray-mpich/8.1.21
            mpi_env_vars:
              - ESMF_MPIRUN=mpiexec
