machine:
  name: hearhear
  cores_per_node: 8
  scheduler: None
  # Since we don't submit to compute nodes on this machine, there is no notion of a head node
  # (this bypasses the ssh'ing to the head node in doing the ESMPy installation)
  head_node_name: null

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]

matrix:

  gfortranclang:
    versions:
      14.1.0_16.0.0:
        compiler: apple-clang/16.0.0-gfortran14.1.0
        extra_module: cmake/3.30.5
        mpi:
          openmpi:
            module: openmpi/5.0.5
            mpi_netcdf: netcdf-c/4.9.2 netcdf-fortran/4.6.1
            mpi_env_vars:
              # There are problems building the trace tests with spack's gfortran, which
              # show up in openmpi builds of ESMF: see
              # https://github.com/spack/spack/issues/46506. Once this duplicate LC_RPATH
              # spack issue is resolved, we can remove the following setting. (This is not
              # really an mpi-related env var, but since we only want to apply this for
              # openmpi, we're using mpi_env_vars.)
              - ESMF_TRACE_LIB_BUILD=OFF
          mpich:
            module: mpich/4.2.3
            mpi_netcdf: netcdf-c/4.9.2 netcdf-fortran/4.6.1
          mpiuni:
            module: None
            mpi_netcdf: netcdf-c-nompi/4.9.2 netcdf-fortran-nompi/4.6.1
        extra_env_vars:
          - ESMPY_DATA_DIR="/Users/sacks/scratch/esmf-testing/esmf-test-data/grids"
        esmpy:
          # This python version corresponds to the suffix in environment-python3.11-numpy1.26.yml
          python: python3.11-numpy1.26

  gfortran:
    versions:
      14.1.0:
        compiler: gcc/14.1.0
        extra_module: cmake/3.30.5
        mpi:
          openmpi:
            module: openmpi/5.0.5
            mpi_netcdf: netcdf-c/4.9.2 netcdf-fortran/4.6.1
          mpich:
            module: mpich/4.2.3
            mpi_netcdf: netcdf-c/4.9.2 netcdf-fortran/4.6.1
          mpiuni:
            module: None
            mpi_netcdf: netcdf-c-nompi/4.9.2 netcdf-fortran-nompi/4.6.1
        extra_env_vars:
          - ESMPY_DATA_DIR="/Users/sacks/scratch/esmf-testing/esmf-test-data/grids"
        esmpy:
          # This python version corresponds to the suffix in environment-python3.11-numpy1.26.yml
          python: python3.11-numpy1.26  