machine:
  name: izumi
  cores_per_node: 48
  scheduler:
    type: pbs
    account: UNUSED
    queue: medium
    pbs_node_specifier: nodes_ppn

test:
  esmf_branch: [feature/hconfig-extras]
  nuopc_branch: [develop]
  filter:
    compiler: [intel, gfortran, nag]
    mpi: [mpiuni]

matrix:
  intel:
    test_time: "3:00:00"
    versions:
      20.0.1:
        compiler: compiler/intel/20.0.1
        netcdf: tool/netcdf/4.7.4/intel/20.0.1
        mpi:
          mpiuni:
            module: None
          mvapich2:
            module: mpi/2.3.3/intel/20.0.1
          openmpi:
            module: openmpi/intel/20.0.1

  gfortran:
    test_time: "3:00:00"
    versions:
      9.3.0:
        compiler: compiler/gnu/9.3.0
        netcdf: tool/netcdf/4.7.4/gnu/9.3.0
        mpi:
          mpiuni:
            module: None
          mvapich2:
            module: mpi/2.3.3/gnu/9.3.0
          openmpi:
            module: openmpi/4.0.3/gnu/9.3.0

  nag:
    test_time: "3:00:00"
    versions:
      7.0:
        compiler: compiler/nag/7.0
        netcdf: tool/netcdf/c4.7.4-f4.5.2/nag-gnu/7.0-9.3.0
        mpi:
          mpiuni:
            module: None
          mvapich2:
            module: mpi/2.3.3/nag/7.0
          openmpi:
            module: openmpi/4.0.3/nag/7.0
        extra_env_vars:
          - ESMF_NETCDFF_LIBS=/usr/local/netcdf-c-4.7.4-f-4.5.2-gcc-g++-9.3.0-nag-7.0/lib/libnetcdff.a

  nvhpc:
    test_time: "3:00:00"
    versions:
      22.11:
        compiler: None
        netcdf: tool/netcdf/4.9.0/hpc-sdk
        mpi:
          mpiuni:
            module: compiler/nvhpc-nompi/22.11
          openmpi:
            module: compiler/nvhpc/22.11
        extra_env_vars:
          - ESMF_NETCDF_INCLUDE="$NETCDF_PATH/include"
          - ESMF_NETCDF_LIBPATH="$NETCDF_PATH/lib"
