machine:
  name: jet
  cores_per_node: 24
  scheduler:
    type: slurm
    account: esmf
    queue: batch
    partition: xjet

test:
  esmf_branch: [develop]
  nuopc_branch: [develop]
  filter:
    compiler: [gfortran]

matrix:
  intel:
    test_time: "2:00:00"
    versions:
      19.1.2:
        compiler: intel/2020.2
        netcdf: netcdf/4.7.0
        mpi:
          intelmpi:
            module: impi/2020.2
            mpi_env_vars:
              - ESMF_MPIRUN=mpirun.srun
        extra_module: cmake/3.28.1

  gfortran:
    test_time: "2:00:00"
    versions:
      13.2.0:
        compiler: gnu/13.2.0
        netcdf: None
        mpi:
          openmpi:
            module: openmpi/4.1.6
            mpi_env_vars:
              - ESMF_MPIRUN=mpirun.srun
        extra_module: cmake/3.28.1

  nvhpc:
    test_time: "1:30:00"
    build_time: "1:20:00"
    versions:
      23.3:
        compiler: nvhpc/23.3
        netcdf: None
        mpi:
          mpiuni:
            module: None
          openmpi:
            module: None
            mpi_env_vars:
              - ESMF_MPIRUN=mpirun
        extra_module: cmake/3.28.1
