machine:
  name: jet
  cores_per_node: 24
  scheduler:
    type: slurm
    account: hfv3gfs
    queue: batch
    partition: xjet

test:
  esmf_branch: [develop,fix/nag]
  nuopc_branch: [develop,develop]

matrix:
  intel:
    test_time: "2:00:00"
    versions:
      19.1.2:
        compiler: intel/2020.2
        netcdf: netcdf/4.7.0
        mpi:
          intelmpi:
            module: impi/2020.2
            mpi_env_vars:
              - ESMF_MPIRUN=mpirun.srun
        extra_module: cmake

  gfortran:
    test_time: "2:00:00"
    versions:
      9.2.0:
        compiler: gnu/9.2.0
        netcdf: None
        mpi:
          openmpi:
            module: openmpi/3.1.4
            mpi_env_vars:
              - ESMF_MPIRUN=mpirun.srun
        extra_module: cmake

  nvhpc:
    test_time: "1:30:00"
    build_time: "1:20:00"
    versions:
      22.2:
        compiler: nvhpc/22.2
        netcdf: None
        mpi:
          mpiuni:
            module: None
          intelmpi:
            module: impi/2022.3.0
            mpi_env_vars:
              - ESMF_MPIRUN=mpirun.srun
              - ESMF_F90=mpinvf90
              - ESMF_CXX=mpinvc++
              - ESMF_C=mpinvc
        extra_module: cmake
