machine:
  name: onyx
  cores_per_node: 44
  scheduler:
    type: pbs
    account: NRLMR03795024
    queue: standard

test:
  esmf_branch: [develop,update_json]
  nuopc_branch: [develop,develop]

matrix:
  intel:
    versions:
      2017.5:
        compiler: intel/17.0.5.239
        netcdf: netcdf/intel-17.0.1.132/4.4.1.1
        mpi:
          mpi:
            module: cray-mpich/7.7.12
            mpi_env_vars:
              - ESMF_F90COMPILER=ftn
        extra_module: PrgEnv-intel
        unload_module: "PrgEnv-cray PrgEnv-gnu"
  gfortran:
    test_time: "2:00:00"
    versions:
      7.2.0:
        compiler: gcc/7.2.0
        netcdf: netcdf/gcc-7.3.0/4.6.2
        mpi:
          mpi:
            module: cray-mpich/7.7.12
            mpi_env_vars:
              - ESMF_F90COMPILER=ftn
          mpiuni:
            module: None
        extra_module: PrgEnv-gnu
        unload_module: "PrgEnv-cray PrgEnv-intel"
