machine: onyx
account: NRLMR03795024
queue: standard
scheduler: pbs
corespernode: 44
compiler: [gfortran]
branch: [develop]
#nuopcbranch: develop
intel:
     versions: 
       2017.5: 
         compiler: intel/17.0.5.239          
         netcdf: netcdf/intel-17.0.1.132/4.4.1.1
         mpi:
           mpi:
             module: cray-mpich/7.7.12     
             mpi_env_vars:
               var1: ESMF_F90COMPILER=ftn
     extramodule: PrgEnv-intel
     unloadmodule: "PrgEnv-cray PrgEnv-gnu"
gfortran:
     test_time: "2:00:00"
     versions: 
       7.2.0: 
         compiler: gcc/7.2.0
         netcdf: netcdf/gcc-7.3.0/4.6.2  
         mpi:
           mpi:
             module: cray-mpich/7.7.12     
             mpi_env_vars:
               var1: ESMF_F90COMPILER=ftn
           mpiuni: 
             module: None
     extramodule: PrgEnv-gnu
     unloadmodule: "PrgEnv-cray PrgEnv-intel"
