machine:
  name: perlmutter
  lustre: True
  wait_to_collect: True
  cores_per_node: 128
  scheduler:
    type: slurm
    account: e3sm
    queue: regular
    constraint: cpu

test:
  esmf_branch: [feature/use_yaml]
  nuopc_branch: [feature/use_yaml]
#  filter:
#    compiler: [gfortran]

matrix:
  gfortran:
    test_time: "3:00:00"
    versions:
      11.2.0:
        compiler: gcc/11.2.0
        netcdf: cray-hdf5/1.12.2.1 cray-netcdf/4.9.0.1
        mpi:
          mpiuni: 
            module: None
          mpi: 
            module: cray-mpich/8.1.22
        extra_env_vars: 
          - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
        extra_module: PrgEnv-gnu cpu

  aocc:
    test_time: "4:00:00"
    versions:
      3.2.0:
        compiler: aocc/3.2.0
        netcdf: cray-hdf5/1.12.2.1 cray-netcdf/4.9.0.1
        mpi:
          mpiuni: 
            module: None
          mpi: 
            module: cray-mpich/8.1.22
        extra_env_vars: 
          - ESMF_NETCDF_LIBS="-lnetcdff -lnetcdf"
        extra_module: PrgEnv-aocc cpu
