#!/usr/bin/expect --
 
set test_type [lindex $argv 0]
set ESMF_DIR [lindex $argv 1]
set ESMF_BOPT [lindex $argv 2]
set ESMF_COMM [lindex $argv 3]
set NUM_PETS [lindex $argv 4]
set ksh_pid [spawn /bin/bash]


set prompt "(%|>|#|\\$) $"          ;# default prompt

catch {set prompt $env(EXPECT_PROMPT)}

expect -re $prompt

send "export ESMF_OS=`uname -s` \r"

expect -re $prompt

send "export ESMF_COMPILER=intel \r"

expect -re $prompt

send "export ESMF_SITE=default \r"

expect -re $prompt

send "cd $ESMF_DIR \r"

#expect -re $prompt

#set timeout 3700
#spawn  bsub  -Ip -q small -W 2:00 -n 12 -P UCUB0024 /bin/bash 
#spawn  bsub  -Ip -q small -W 2:00 -n 12 -P P35071386  /bin/bash 
#spawn  bsub  -Ip -q small -W 2:00 -n 12 -P SCSG0002  /bin/bash 

set timeout 36000

#set prompt "(%|>|#|\\$) $"          ;# default prompt

#catch {set prompt $env(EXPECT_PROMPT)}

expect {
        -re $prompt
                {
                        send " cd $ESMF_DIR\r"
                }
        timeout
                {
                        puts "no queue available " ;
                        set file [ open queue_results w]
                        puts $file "failed"
                        send \003

                        expect {
                                -re $prompt
                                        {
                                                send "echo '1'\r"
                                        }
                                "terminated"
                                        {
                                                send " \r"
                                        }
                                }
                }
        }



#set prompt "(%|>|#|\\$) $"          ;# default prompt

#catch {set prompt $env(EXPECT_PROMPT)}

expect {
        -re $prompt
                {
                        send "echo '5'\r"
                }
        eof
                {
                        exit 1
                }
        }

send "echo '4'\r"
puts "Got a queue "
set file [ open queue_results w]
puts $file "passed"


expect -re $prompt

send "cd $ESMF_DIR \r"

expect -re $prompt

#send "export MPIRUN=$ESMF_DIR/scripts/mpirun.ibmpjl \r"

#expect -re $prompt


send "export NUM_PETS=$NUM_PETS \r"

expect -re $prompt

send "export ESMF_NUM_PROCS=16 \r"

expect -re $prompt

set timeout 36000

if { $test_type == "ESMF_RegridWeightGenCheck" } {

		send "cd $ESMF_DIR/../esmf-extended-tests/ESMF_RegridWeightGenCheck \r"
		expect -re $prompt
                send "gmake run 1>  regridwgc.out  2>&1  \r"

} elseif { $test_type == "ESMF_MOABCheck" } {

                send "cd $ESMF_DIR/../esmf-extended-tests/ESMF_MOABCheck \r"
		expect -re $prompt
		# Passes only if run a one PET
                send "$ESMF_DIR/scripts/mpirun.ibmpjl -np 4 ./ESMF_MOABCheck > moab.out 2>&1 \r"
		expect -re $prompt
                send "cd $ESMF_DIR \r"

}
 
expect {
	-re $prompt
                        {
        
                                send "exit\r"
        
                        }
        "completed"
                        {

                                send "\r"

                        }

        }

expect -re $prompt

