#!/bin/bash -l
 
test_type=$1
ESMF_DIR=$2
ESMF_BOPT=$3
ESMF_COMM=$4
SYS_TEST_TYPE=$5
U_TEST_TYPE=$6
U_TESTS=$7
THREADED=$8
homedir=$9
APPSDIR=${10}
LOGDIR=${11}

cd $ESMF_DIR

if [[ $U_TESTS == "EX" ]]; then
  export ESMF_TESTEXHAUSTIVE=ON
else
  export ESMF_TESTEXHAUSTIVE=OFF
fi

if [[ $THREADED == "THREADED" ]]; then
  export ESMF_TESTWITHTHREADS=ON
else
  export ESMF_TESTWITHTHREADS=OFF
fi

if [[ $test_type == "demo" ]]; then
  if [[ $SYS_TEST_TYPE == "UNI" ]]; then
    make run_demos_uni 1> tmp 2>&1
    cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_demos_uni_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out 
  else
    make run_demos 1> tmp 2>&1
    cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_demos_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  fi
  
elif [[ $test_type == "sys_test" ]]; then
  if [[ $SYS_TEST_TYPE == "UNI" ]]; then
    make run_system_tests_uni 1> tmp 2>&1
    cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_system_tests_uni_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  else
    make run_system_tests 1> tmp 2>&1
    cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_system_tests_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  fi

elif [[ $test_type == "examples" ]]; then
  if [[ $SYS_TEST_TYPE == "UNI" ]]; then
    make run_examples_uni 1> tmp 2>&1
	cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_examples_unit_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  else
    make run_examples 1> tmp 2>&1
	cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_examples_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  fi

elif [[ $test_type == "unit" ]]; then
  if [[ $U_TEST_TYPE == "UNI" ]]; then
    make run_unit_tests_uni 1> tmp 2>&1
	cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_unit_tests_uni_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  else
    make run_unit_tests 1> tmp 2>&1
	cp -rf $ESMF_DIR/tmp  /home1/07356/tg866552/storage/develop/run_unit_tests_$ESMF_OS$ESMF_ABI$ESMF_COMPILER$ESMF_COMM.out
  fi

elif [[ $test_type == "apps_test" ]]; then
  cd $APPSDIR
  $homedir/apps_test
fi

