#!/bin/bash --login

######### Start the mail message file ################################


echo "" > $LOGDIR/mailHeader
echo "" > $LOGDIR/header
echo "Script end: `date`" >> $LOGDIR/header


echo "" >> $LOGDIR/mailMessage
echo "" >> $LOGDIR/mailMessage
echo "" >> $LOGDIR/mailHeader
echo "" >> $LOGDIR/mailHeader
echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header

echo "_______________________ESMF TRUNK EXTERNAL DEMOS AND BFB TEST SUMMARY_____________________________" >> $LOGDIR/header

echo "" >> $LOGDIR/header


echo "               BUILD       INSTALL    OS.COMPILER.COMM.ABI       external demos     bfb compare">> $LOGDIR/header

echo "_________________________________________________________________________________________________" >> $LOGDIR/header

echo "               PASS/FAIL   PASS/FAIL                              PASS/FAIL/SKIP"    PASS/FAIL/NOTFOUND  >> $LOGDIR/header

echo "________________________________________________________________________________________________" >> $LOGDIR/header





############################# Put the mail message together and mail it ####################

# Put all the files together
# First fix the summmary file

if grep "normal" $homedir/test_results
then
        echo ""
else
        echo "WARNING: The test experienced an abnormal termination during execution," >> $LOGDIR/mailHeader
        echo "         therefore the test results may be incomplete/invalid." >> $LOGDIR/mailHeader
        echo "" >> $LOGDIR/mailHeader
        # Set test status as orange, if it is not red
        if !(grep "red" $LOGDIR/Test_Status)
        then
                echo "Test_results:orange" > $LOGDIR/Test_Status
        fi

fi

awk '{if ($1 ~/PASS/ && $2 ~/PASS/ ) printf ("%-16s%-12s%-8s%-25s%10s%15s%15s\n",  $3, $1, $2, $4, $5, $6, $7) ;else  if ($1 ~/FAIL/) printf ("%-10s%-20s%-10s\n", $2, $1,  $3 );else printf ("%-16s%-12s%-8s\n", $3, $1, $2 )}'  $LOGDIR/summary > $LOGDIR/newsummary

cat $LOGDIR/mailHeader $LOGDIR/header $LOGDIR/newsummary > $LOGDIR/sum
cat $LOGDIR/sum $LOGDIR/mailMessage > $LOGDIR/newMailMessage
echo "" >>  $LOGDIR/newMailMessage
echo " The tarballs of the tests and examples directories can be found at:" >>  $LOGDIR/newMailMessage
echo " $LOGDIR." >>  $LOGDIR/newMailMessage
echo " These tarballs contain the *Log and *stdout files only, not the executables." >>  $LOGDIR/newMailMessage
echo " This directory also contains failed build output files with the naming convention of " >>  $LOGDIR/newMailMessage
echo " build_ESMF_BOPT_(day)(platform)ESMF_OS ESMF_ABI ESMF_COMPILER ESMF_COMM." >>  $LOGDIR/newMailMessage
echo " For example, if the build fails on longs on the 19th of the month with ESMF_BOPT=g, the file " >>  $LOGDIR/newMailMessage
echo " would be called 'build_g_19longslinux32pgimpiuni'." >>  $LOGDIR/newMailMessage

