#!/bin/bash --login

######### Start the mail message file ################################


echo "" > $LOGDIR/mailHeader
echo "" > $LOGDIR/header
echo "Script end: `date`" >> $LOGDIR/header



echo "" >> $LOGDIR/mailMessage
echo "" >> $LOGDIR/mailMessage
echo "" >> $LOGDIR/mailHeader
echo "" >> $LOGDIR/mailHeader
echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "______________________________________ESMF BUILD AND TEST SUMMARY___________________________" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "" >> $LOGDIR/header
echo "                                            " >> $LOGDIR/header
echo "                    INSTALL/" >> $LOGDIR/header
echo "           BUILD  QUICK_START OS.COMPILER.COMM.ABI    UNIT TESTS   EXAMPLES  SYSTEM TESTS  APPS TESTS">> $LOGDIR/header

echo "_____________________________________________________________________________________________________" >> $LOGDIR/header

echo "          PASS/FAIL PASS/FAIL                           PASS/FAIL   PASS/FAIL  PASS/FAIL   PASS/FAIL">> $LOGDIR/header

echo "_____________________________________________________________________________________________________" >> $LOGDIR/header


############################# Put the mail message together and mail it ####################

awk '{if ($1 ~/PASS/) printf ("%-12s%-10s%-8s%-25s%10s%10s%10s%10s\n",  $3, $1, $2, $4, $5, $6, $7, $8) ;else  printf ("%-10s%-20s%-10s\n", $2, $1,  $3 )}'  $LOGDIR/summary > $LOGDIR/newsummary
cat $LOGDIR/mailHeader $LOGDIR/header $LOGDIR/newsummary > $LOGDIR/sum
cat $LOGDIR/sum $LOGDIR/mailMessage > $LOGDIR/newMailMessage
echo "" >>  $LOGDIR/newMailMessage

echo " The tarballs of the tests and examples directories can be found at:" >>  $LOGDIR/newMailMessage
echo " $LOGDIR." >>  $LOGDIR/newMailMessage
echo " These tarballs contain the *Log and *stdout files only, not the executables." >>  $LOGDIR/newMailMessage
echo " This directory also contains failed build output files with the naming convention of " >>  $LOGDIR/newMailMessage
echo " build_ESMF_BOPT_(day)(platform)ESMF_OS ESMF_ABI ESMF_COMPILER ESMF_COMM." >>  $LOGDIR/newMailMessage
echo " For example, if the build fails on longs on the 19th of the month with ESMF_BOPT=g, the file " >>  $LOGDIR/newMailMessage
echo " would be called 'build_g_Stampedelinux32iintelimpi'." >>  $LOGDIR/newMailMessage
