#!/usr/bin/env bash

###############################################################################
#
#  Harvest the APIs from the html version of the reference manual from two 
#  different tags and then diff them to make a report of the interface changes.
#
###############################################################################

# usage: sh _harvestAPIs <dir_of_esmf_with_final_backslash> <tag_of_baseline> <tag_of_new_release>

# parse the input arguments
#ESMF_DIR=$1
#TAG1=$2
#TAG2=$3

# set up directories and build variables
HERE=$PWD
export ESMF_DIR=$ESMF_DIR
export TAG2=$TAG2

# build the first tag and associated documentation
cd $ESMF_DIR
git fetch
git checkout tags/$TAG1
git branch -a
make doc
cd $HERE

python -c 'print "starting harvestAPIsFromRefDoc on $TAG1"'

# collect apis from the first tag
python -c 'import harvestAPIsFromRefDoc as h; h.harvest_APIs("'$ESMF_DIR'", "APIs-'$TAG1'.out")'

#dryrun
python -c 'import harvestAPIsFromRefDoc as h; h.harvest_APIs("'$ESMF_DIR'", "'$TAG1'")'

python -c 'print "finishing harvestAPIsFromRefDoc on $TAG1"'

# build the second tag and associated documentation
cd $ESMF_DIR
git fetch
git checkout tags/$TAG2
git branch -a
make distclean
make doc
cd $HERE

python -c 'print "starting harvestAPIsFromRefDoc on $TAG2"'

# collect apis from the second tag
python -c 'import harvestAPIsFromRefDoc as h; h.harvest_APIs("'$ESMF_DIR'", "APIs-'$TAG2'.out")'

#dryrun
python -c 'import harvestAPIsFromRefDoc as h; h.harvest_APIs("'$ESMF_DIR'", "'$TAG2'")'


python -c 'print "finishing harvestAPIsFromRefDoc on $TAG2"'


# diff the apis from both tags and create a report
diff 'APIs-'$TAG1'.out' 'APIs-'$TAG2'.out' > 'diff-'$TAG1'-'$TAG2'.out'

