#!/usr/bin/env bash

set -Eeuxo pipefail

###############################################################################
#
#  Harvest the APIs from the html version of the reference manual from two 
#  different tags and then diff them to make a report of the interface changes.
#
###############################################################################

# set up directories and build variables
HERE=$PWD

if [[ -z ${ESMF_DIR+x} ]]; then
    echo "ERROR: ESMF_DIR is not defined"
    exit -1
fi
if [[ -z ${TAG1+x} ]]; then
    echo "ERROR: TAG1 is not defined"
    exit -1
fi
if [[ -z ${TAG2+x} ]]; then
    echo "ERROR: TAG2 is not defined"
    exit -1
fi

if [ ! -d ${ESMF_DIR} ] 
then
    echo "ESMF_DIR does not exist: $ESMF_DIR"
    exit -1
fi

export ESMF_DIR=$ESMF_DIR
export TAG1=$TAG1
export TAG2=$TAG2

export TAG1NAME="`echo $TAG1 | sed 's#/#_#'`"
export TAG2NAME="`echo $TAG2 | sed 's#/#_#'`"

# build the first tag and associated documentation
cd $ESMF_DIR
git fetch --all
git fetch --all --tags
git checkout $TAG1
git branch -a
make doc
cd $HERE

echo "START harvest APIs on $TAG1"
./harvestAPIsFromRefDoc.py $ESMF_DIR "APIs-$TAG1NAME.out"
echo "FINISH harvest APIs on $TAG1"

# build the second tag and associated documentation
cd $ESMF_DIR
git checkout $TAG2
git branch -a
make distclean
make doc
cd $HERE

echo "START harvest APIs on $TAG2"
./harvestAPIsFromRefDoc.py $ESMF_DIR "APIs-$TAG2NAME.out"
echo "FINISH harvest APIs on $TAG2"

cd $HERE

# diff the apis from both tags and create a report
diff 'APIs-'$TAG1NAME'.out' 'APIs-'$TAG2NAME'.out' > 'diff-'$TAG1NAME'-'$TAG2NAME'.out'

